module.exports = {
  en: [
    {
      title: "Developing AI Systems through Data-driven Learning of Generalized Interpretable Knowledge from Background Knowledge and Limited Data",
      url: "https://kaken.nii.ac.jp/en/grant/KAKENHI-PROJECT-25K21269/",
      role: "Principal Investigator",
      amount: "￥ 4,680,000",
      program: "Grant-in-Aid for Early-Career Scientists",
      sponsor: "Japan Society for the Promotion of Science",
      span: "April 2025 - March 2027",
    },
    {
      title: "Constraint Reasoning for Trustworthy AI",
      url: "https://kaken.nii.ac.jp/en/grant/KAKENHI-PROJECT-25K03190/",
      role: "Co-Investigator",
      amount: "￥ 18,720,000",
      program: "Grant-in-Aid for Scientific Research (B)",
      sponsor: "Japan Society for the Promotion of Science",
      span: "April 2025 - March 2028",
    },
    {
      title: "Discovering New Knowledge by Combining Symbolic Logic and Deep Learning",
      url: "https://kaken.nii.ac.jp/en/grant/KAKENHI-PROJECT-22K21302",
      role: "Principal Investigator",
      amount: "￥ 2,860,000",
      program: "Grants-in-Aid for Scientific Research Grant-in-Aid for Research Activity Start-up",
      sponsor: "Japan Society for the Promotion of Science",
      span: "August 2022 - March 2024",
    },
    {
      title: "Towards Reliable Generative AI by Logical Reasoning",
      url: "https://www.nii.ac.jp/research/upload/2024NIIkobogatakyodokenkyusaitakuitiran.pdf",
      role: "Principal Investigator",
      amount: "￥ 975,000",
      program: "Open Collaborative Research",
      sponsor: "National Institute of Informatics",
      span: "July 2024 - March 2025",
    },
    {
      title: "Research on Intelligence and Consciousness",
      url: "https://www.iir.titech.ac.jp/ofr/en/academy3_2023.html",
      role: "Principal Investigator",
      amount: "￥ 950,000",
      program: "New Research Challenge Incentive Fund",
      sponsor: "Organization for Fundamental Research, Tokyo Institute of Technology",
      span: "September 2023 - March 2025",
    },
    {
      title: "Robust AI by Integration of Knowledge Representation and Machine Learning",
      url: "https://kaken.nii.ac.jp/en/grant/KAKENHI-PROJECT-21H04905",
      role: "Co-Investigator",
      amount: "￥ 41,470,000",
      program: "Grant-in-Aid for Scientific Research (A)",
      sponsor: "Japan Society for the Promotion of Science",
      span: "April 2022 - March 2025",
    },
    {
      title: "Understandable Model by Combination of Symbolic Machine Learning and Deep Statistical Learning",
      url: "https://kaken.nii.ac.jp/grant/KAKENHI-PROJECT-21J14367",
      role: "Research Fellow",
      amount: "￥ 1,500,000",
      program: "Grants-in-Aid for Scientific Research Grant-in-Aid for JSPS Fellows",
      sponsor: "Japan Society for the Promotion of Science",
      span: "April 2021 - March 2022",
    },
  ],
  ja: [
    {
      title: "背景知識と少量のデータから汎用的で解釈可能な知識をデータ駆動で学習するAIの開発",
      url: "https://kaken.nii.ac.jp/ja/grant/KAKENHI-PROJECT-25K21269/",
      role: "代表",
      amount: "￥ 4,680,000",
      program: "科学研究費助成事業 若手研究",
      sponsor: "日本学術振興会",
      span: "2025年4月 - 2027年3月",
    },
    {
      title: "信頼されるAIに向けた制約推論",
      url: "https://kaken.nii.ac.jp/ja/grant/KAKENHI-PROJECT-25K03190/",
      role: "分担",
      amount: "￥ 18,720,000",
      program: "科学研究費助成事業 基盤研究(B)",
      sponsor: "日本学術振興会",
      span: "2025年4月 - 2028年3月",
    },
    {
      title: "記号論理と深層機械学習の統合による新たな知識を発見するAIに関する研究",
      url: "https://kaken.nii.ac.jp/ja/grant/KAKENHI-PROJECT-22K21302",
      role: "代表",
      amount: "￥ 2,860,000",
      program: "科学研究費助成事業 研究活動スタート支援",
      sponsor: "日本学術振興会",
      span: "2022年8月 - 2024年3月",
    },
    {
      title: "論理的推論が可能な「信頼できる生成AI」の実現",
      url: "https://www.nii.ac.jp/research/upload/2024NIIkobogatakyodokenkyusaitakuitiran.pdf",
      role: "代表",
      amount: "￥ 975,000",
      program: "公募型共同研究",
      sponsor: "国立情報学研究所",
      span: "2024年7月 - 2025年3月",
    },
    {
      title: "知能や意識についての研究",
      url: "https://www.iir.titech.ac.jp/ofr/academy3_2023.html",
      role: "代表",
      amount: "￥ 500,000",
      program: "新研究挑戦奨励金",
      sponsor: "基礎研究機構　東京工業大学",
      span: "2023年9月 - 2024年3月",
    },
    {
      title: "知識表現・推論と機械学習の統合によるロバストAIの実現",
      url: "https://kaken.nii.ac.jp/en/grant/KAKENHI-PROJECT-21H04905",
      role: "分担",
      amount: "￥ 41,470,000",
      program: "科学研究費助成事業 基盤研究(A)",
      sponsor: "日本学術振興会",
      span: "2022年4月 - 2025年3月",
    },
    {
      title: "記号論理機械学習と深層機械学習の融合による理解可能なモデルを構築する研究",
      url: "https://kaken.nii.ac.jp/ja/grant/KAKENHI-PROJECT-21J14367",
      role: "特別研究員",
      amount: "￥ 1,500,000",
      program: "科学研究費助成事業 特別研究員奨励費",
      sponsor: "日本学術振興会",
      span: "2021年4月 - 2022年3月",
    },
  ],
};
